package one.show.live.common.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import one.show.live.common.po.POLogin;

import one.show.live.common.greendao.POLoginDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pOLoginDaoConfig;

    private final POLoginDao pOLoginDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pOLoginDaoConfig = daoConfigMap.get(POLoginDao.class).clone();
        pOLoginDaoConfig.initIdentityScope(type);

        pOLoginDao = new POLoginDao(pOLoginDaoConfig, this);

        registerDao(POLogin.class, pOLoginDao);
    }
    
    public void clear() {
        pOLoginDaoConfig.clearIdentityScope();
    }

    public POLoginDao getPOLoginDao() {
        return pOLoginDao;
    }

}
